apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks_cluster
  region: us-east-1

#Name,Instancetype,AZ,Desired Capacity
managedNodeGroups: # this is also completely managed by AWS
  - name: spot
    instanceType: t2.medium
    # your K8 node can be anytime taken back by AWS
    spot: true
    availabilityZones: # ebs static provisioning
    - us-east-1c
    desiredCapacity: 2
    ssh:
      publicKeyName: terraform # replace this with your keypair exists in AWS.