#Command to run = docker-compose up -d
#Use the host’s IP address, not the container’s IP, even on a custom bridge. 
#You’re mapping container’s port to the host with -p, and that’s what makes it reachable via browser.
networks:
  roboshop:
    driver: bridge
volumes:
  web:
services: 
  web:
    image: web:1
    container_name: web
    networks: 
      - roboshop
    ports: 
      - "80:80"
    volumes:
      - web:/usr/share/nginx/html/ 
    #Long syntax of volume declarationSS
    # volumes:
    #   - type: volume
    #     source: web
    #     target: /usr/share/nginx/html/
    
    #  # environment:
    #   - user=roboshop
    #   - pass=roboshop123
    # depends_on:
    #   - catalogue
    #   - user 
   
  #command: Optional, replace the default CMD specified by the image..